import DOMPurify, { Config } from 'dompurify';

/**
 * Strict DOMPurify sanitization configuration for Custom Markdown, HTML Callouts, and SVGs.
 * Protects against XSS, script injection, iframe hijacking, and dangerous URL protocols.
 */

// Allowed URL protocols
const SAFE_URL_PROTOCOLS = /^(?:(?:https?|mailto|tel|ftp):|#|\/|\.\/|\.\.\/)/i;
const DANGEROUS_PROTOCOLS = /^(?:javascript|data|vbscript|file|about):/i;

/**
 * Validates and sanitizes a URL string to prevent javascript: or malicious data: execution.
 * If the URL is unsafe, returns '#' or a safe fallback.
 */
export function sanitizeUrl(url: string | null | undefined, fallback: string = '#'): string {
  if (!url || typeof url !== 'string') return fallback;

  const trimmed = url.trim().replace(/[\u0000-\u001F\u007F-\u009F\s]+/g, ''); // strip invisible control chars

  if (DANGEROUS_PROTOCOLS.test(trimmed)) {
    // Allow safe data URIs for images only (e.g. data:image/png;base64,...)
    if (/^data:image\/(?:png|jpeg|jpg|gif|webp|svg\+xml);base64,/i.test(trimmed)) {
      return trimmed;
    }
    return fallback;
  }

  if (SAFE_URL_PROTOCOLS.test(trimmed) || !trimmed.includes(':')) {
    return trimmed;
  }

  return fallback;
}

/**
 * Configure global DOMPurify hooks
 */
let isPurifyHookConfigured = false;
function configurePurifyHooks() {
  if (isPurifyHookConfigured || typeof window === 'undefined') return;

  // Ensure all external links have rel="noopener noreferrer"
  DOMPurify.addHook('afterSanitizeAttributes', (node) => {
    if (node.tagName === 'A') {
      const href = node.getAttribute('href');
      if (href && (href.startsWith('http://') || href.startsWith('https://') || href.startsWith('//'))) {
        node.setAttribute('target', '_blank');
        node.setAttribute('rel', 'noopener noreferrer');
      }
    }
    // Prevent image error event hijack
    if (node.tagName === 'IMG') {
      node.removeAttribute('onerror');
      node.removeAttribute('onload');
    }
  });

  isPurifyHookConfigured = true;
}

configurePurifyHooks();

/**
 * Sanitizes HTML content for Markdown rendering, custom callouts, and formatted blocks.
 */
export function sanitizeHtml(dirtyHtml: string, options?: Config): string {
  if (!dirtyHtml || typeof dirtyHtml !== 'string') return '';

  return String(
    DOMPurify.sanitize(dirtyHtml, {
      ALLOWED_TAGS: [
        'a', 'abbr', 'b', 'bdi', 'bdo', 'blockquote', 'br', 'caption', 'cite', 'code', 'col',
        'colgroup', 'dd', 'del', 'details', 'dfn', 'div', 'dl', 'dt', 'em', 'figcaption',
        'figure', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'img', 'ins', 'kbd',
        'li', 'mark', 'ol', 'p', 'pre', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'small',
        'span', 'strong', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'tfoot', 'th',
        'thead', 'time', 'tr', 'u', 'ul', 'var', 'wbr'
      ],
      ALLOWED_ATTR: [
        'href', 'title', 'target', 'rel', 'src', 'alt', 'width', 'height', 'class', 'id',
        'style', 'align', 'valign', 'dir', 'lang', 'open', 'role', 'aria-label',
        'aria-hidden', 'data-*'
      ],
      ALLOW_DATA_ATTR: true,
      ADD_ATTR: ['target', 'rel'],
      FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'form', 'input', 'button', 'select', 'textarea', 'meta', 'link', 'base', 'applet'],
      FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'onchange', 'onsubmit', 'formaction'],
      RETURN_TRUSTED_TYPE: false,
      ...options
    })
  );
}

/**
 * Sanitizes SVG markup generated by Mermaid diagrams or custom SVG components.
 * Retains vector graphics, markers, and path definitions while stripping executable scripts.
 */
export function sanitizeSvg(dirtySvg: string, options?: Config): string {
  if (!dirtySvg || typeof dirtySvg !== 'string') return '';

  return String(
    DOMPurify.sanitize(dirtySvg, {
      USE_PROFILES: { svg: true, svgFilters: true },
      ALLOWED_TAGS: [
        'svg', 'g', 'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon',
        'text', 'tspan', 'defs', 'marker', 'style', 'clipPath', 'pattern', 'linearGradient',
        'radialGradient', 'stop', 'use', 'desc', 'title', 'foreignObject', 'feDropShadow',
        'feGaussianBlur', 'feMerge', 'feMergeNode', 'feColorMatrix', 'feComponentTransfer',
        'feFuncA', 'feFuncR', 'feFuncG', 'feFuncB', 'filter'
      ],
      ALLOWED_ATTR: [
        'viewBox', 'xmlns', 'fill', 'stroke', 'stroke-width', 'stroke-dasharray', 'stroke-linecap',
        'stroke-linejoin', 'stroke-opacity', 'fill-opacity', 'd', 'transform', 'class', 'id',
        'x', 'y', 'dx', 'dy', 'width', 'height', 'rx', 'ry', 'cx', 'cy', 'r', 'x1', 'y1',
        'x2', 'y2', 'opacity', 'marker-end', 'marker-start', 'marker-mid', 'markerWidth',
        'markerHeight', 'refX', 'refY', 'orient', 'style', 'font-family', 'font-size',
        'font-weight', 'text-anchor', 'dominant-baseline', 'points', 'offset', 'stop-color',
        'stop-opacity', 'gradientUnits', 'patternUnits', 'clip-path', 'mask', 'filter',
        'preserveAspectRatio', 'textLength', 'lengthAdjust', 'xlink:href', 'href'
      ],
      FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'audio', 'video', 'applet', 'meta', 'link'],
      FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'formaction'],
      ...options
    })
  );
}
